name: 'Aggregate Worker'
description: 'Aggregate files from a worker'
inputs:
  worker:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Fetch results of ${{ inputs.worker }}
      id: restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.REPO }}
        key: apt-repo-${{ inputs.worker }}-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          apt-repo-${{ inputs.worker }}-${{ github.sha }}-${{ github.run_id }}
    - name: Aggregate files
      shell: bash
      if: steps.restore.outputs.cache-matched-key != ''
      run: |
        append_without_header() { if [ -f "$1" ]; then tail -n+2; else cat; fi | tee -a "$1"; }

        cat ${{ env.REPO }}/pkg_build_status.csv | append_without_header ${{ env.AGG }}/pkg_build_status.csv
        cat ${{ env.REPO }}/sources_exact.repos | append_without_header ${{ env.AGG }}/sources_exact.repos
        # local.yaml was already generated during preparation stage

        rm -f ${{ env.REPO }}/pkg_build_status.csv ${{ env.REPO }}/sources_exact.repos ${{ env.REPO }}/local.yaml
        mv ${{ env.REPO }}/* ${{ env.AGG }}
