name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ROS_DISTRO: one
      DEB_DISTRO: jammy
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache/ccache
          key: ccache-${{ env.DEB_DISTRO }}-${{ env.ROS_DISTRO }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ env.DEB_DISTRO }}-${{ env.ROS_DISTRO }}
            ccache-${{ env.DEB_DISTRO }}
      - uses: v4hn/ros-deb-builder-action@rosotest
        timeout-minutes: 350
        with:
          ROS_DISTRO: ${{ env.ROS_DISTRO }}
          DEB_DISTRO: ${{ env.DEB_DISTRO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SBUILD_CONF: '$verbose = 1;'
          ROSDEP_SOURCE: rosdep.yaml
          SQUASH_HISTORY: true
