name: build

on:
  workflow_dispatch:
  push:

jobs:
  ros-robot:
    uses: ./.github/workflows/debs-from-repos.yaml
    with:
      repos: ros-robot
  ros-desktop:
    uses: ./.github/workflows/debs-from-repos.yaml
    needs: ros-robot
    with:
      repos: ros-desktop
      depends: ros-robot
  ros-universe:
    uses: ./.github/workflows/debs-from-repos.yaml
    needs: ros-desktop
    with:
      repos: ros-universe
      depends: ros-desktop
  deploy:
    needs: ros-universe
    if: always()
    runs-on: ubuntu-22.04
    env:
      ROS_DISTRO: one
      DEB_DISTRO: jammy
    steps:
      - name: get apt packages from last job
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/apt_repo
          key: apt-repo-${{ env.DEB_DISTRO }}-${{ env.ROS_DISTRO }}-ros-universe-${{ github.sha }}
      - uses: v4hn/ros-deb-builder-action/deploy@rosotest
        if: always() # alternatively success()
        with:
          ROS_DISTRO: ${{ env.ROS_DISTRO }}
          DEB_DISTRO: ${{ env.DEB_DISTRO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
